version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cf
      POSTGRES_PASSWORD: cfpass
      POSTGRES_DB: cfdb
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  api:
    build: .
    depends_on: [ db ]
    environment:
      DATABASE_URL: postgresql://cf:cfpass@db:5432/cfdb
    ports: ["8000:8000"]
    volumes: [ ".:/app" ]
volumes:
  db_data:
